#!/usr/bin/env bash
# transfer to a web server file
if [ "$#" -ne 4 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"    
else
    path_to_file=$1
    ip=$2
    username=$3
    path_ssh_key=$4
    scp -i "$path_ssh_key" -o StrictHostKeyChecking=no "$path_to_file" "$username@$ip":~/
fi
