#!/usr/bin/env bash
# install nginx and update home_page
sudo apt -y update
apt-get -y install nginx
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
