#!/usr/bin/env bash
# install nginx, update html file, create redirection and restart nginx
sudo apt -y update
sudo apt-get -y install nginx
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html
n="server_name _;\n location \/redirect_me { \n         return 301 youtube.com; \n  }"
sudo sed -i "s/server_name _;/$n/" /etc/nginx/sites-available/default
sudo service nginx restart
