#!/usr/bin/env bash
# install nginx, update html file, create redirection, update 404 error and restart nginx
sudo apt -y update
sudo apt-get -y install nginx
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html
n="server_name _;\n     location \/redirect_me { \n         return 301 youtube.com; \n      }"
sudo sed -i "s/server_name _;/$n/" /etc/nginx/sites-available/default
sudo cp /var/www/html/index.nginx-debian.html /var/www/html/error.html
echo "Ceci n'est pas une page" > /var/www/html/error.html
e="root \/var\/www\/html;\n     error_page 404 \/error.html;"
sudo sed -i "s/root \/var\/www\/html;/$e/" /etc/nginx/sites-available/default
h=$(hostname | grep web | cut -d '-' -f2,3,4)
e="sendfile on;\n       add_header X-Served-By $h;"
sudo sed -i "s/sendfile on;/$e/" /etc/nginx/nginx.conf
sudo service nginx restart
