#!/usr/bin/env bash
# configure the load balancing
sudo apt-get -y update
sudo apt-get -y install haproxy
echo "frontend http
  bind *:80
  mode http
  default_backend web-backend" >> /etc/haproxy/haproxy.cfg
echo "backend web-backend
   mode http
   balance roundrobin
   server 2533-web-01 34.75.49.246:80 check
   server 2533-web-02 104.196.144.160:80 check" >> /etc/haproxy/haproxy.cfg
echo "ENABLED=1" >> /etc/default/haproxy
sudo service haproxy restart
