#!/usr/bin/env bash
# Programs that are detached from the terminal and running in the background
# The general minimum set of instructions is: start, restart and stop. 
# The most popular way of doing so on Unix system is to use the init scripts

if [[ ( $# -gt 1 ) || ( $# == 0 ) ]]
then
	echo "Usage: manage_my_process {start|stop|restart}"
fi

if [[ $1 = "start" ]]
then
	./manage_my_process &
	echo $$ > /var/run/my_process.pid
	echo "manage_my_process started"
elif [[ $1 = "stop" ]]
then
	kill -15 "$(pgrep -f ./manage_my_process)"
	rm /var/run/my_process.pid
	echo "manage_my_process stopped"
elif [[ $1 = "restart" ]]
then
	kill -15 "$(pgrep -f ./manage_my_process)"
	rm /var/run/my_process.pid
	./manage_my_process &
	echo $$ > /var/run/my_process.pid
	echo "manage_my_process restarted"
fi
