#!/usr/bin/env bash
# displays To infinity and beyond indefinitely.and catch sigterm signal 
_f(){
	echo "I am invincible!!!"
}
trap _f SIGTERM
x=1
while [ "$x" ]
do
	echo "To infinity and beyond"
	sleep 2
done
