#!/usr/bin/env bash
# print 10 times holberton using while loop
h='Holberton School'
x=1
while [ $x -lt 11 ]
do
	if [ $x -eq 4 ]
	then
		echo "bad luck";
	elif [ $x -eq 8 ]
	then
		echo "good luck"
	
	else
		echo "$h"
	fi
	x=$(( x + 1 ))
done;
