#!/usr/bin/env bash
# information about holbertonschool file
filename="holbertonschool"
if [ -e $filename ]
then
	if [ -s $filename ]
	then
		echo "holbertonschool file is not empty"
	else
		echo "holbertonschool file is empty"
	fi
	if [ -f $filename ]
	then
		echo "holbertonschool is a regular file"
	fi
	echo "holbertonschool file exists"
else
	echo "holbertonschool file does not exist"
fi
