#!/usr/bin/env bash
# add hostname and ip and do manip for docker container
cp /etc/hosts ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new 
echo "127.0.0.2 localhost" >> ~/hosts.new 
cp -f ~/hosts.new /etc/hosts
